spring:
  application:
    name: mainPage-service
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true
  thymeleaf:
    enabled: true

server:
  #  servlet:
  #    context-path: /api
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id:
      ${spring.application.name}:${spring.application.instance_id:${random.value}}
