--- #DB
spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
--- #Cloud
server:
#  servlet:
#    context-path: /api
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id:
      ${spring.application.name}:${spring.application.instance_id:${random.value}}
--- #mail
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
--- #security & jwt
jwt:
  header: Authorization

  secretKey: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 86400000 # ttl (초)

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh
--- # thymleaf
spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false
    mode: HTML
  mvc:
    static-path-pattern: "/static/**"
  devtools:
    livereload:
      enabled: true